name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          date > generated.txt
          gpg --list-secret-keys --keyid-format=long
