name: Git Mirror Action
on: [push]
jobs:
  m2team:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: qcyblm/m2team.github.io
          ref: 'master'
          persist-credentials: false
          fetch-depth: 0
      - run: |
          date > generated.txt
          git remote add M2Team https://github.com/M2Team/m2team.github.io.git
          git remote -v
          git fetch --all
          git merge M2Team/master
          git push origin master
